package configbuilder

import (
	"bytes"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

type outputConfig struct {
	Events  []eventEntry  `yaml:"events,omitempty"`
	Filters []filterEntry `yaml:"filters,omitempty"`
}

type eventEntry struct {
	Name    string `yaml:"name"`
	Pattern string `yaml:"pattern"`
	State   string `yaml:"state"`
}

type filterEntry struct {
	Name     string   `yaml:"name"`
	Patterns []string `yaml:"patterns"`
}

func BuildConfigYAML(drafts []EventDraft) (string, error) {
	if len(drafts) == 0 {
		return "", fmt.Errorf("no drafts to write")
	}
	out := outputConfig{}
	seen := make(map[string]bool)
	for _, d := range drafts {
		name := strings.TrimSpace(d.EventName)
		pattern := strings.TrimSpace(d.Pattern)
		state := strings.TrimSpace(d.State)
		out.Events = append(out.Events, eventEntry{Name: name, Pattern: pattern, State: state})
		if d.AddFilter {
			filterName := strings.TrimSpace(d.FilterName)
			if !seen[filterName] {
				seen[filterName] = true
				out.Filters = append(out.Filters, filterEntry{Name: filterName, Patterns: []string{pattern}})
			} else {
				for i := range out.Filters {
					if out.Filters[i].Name == filterName {
						out.Filters[i].Patterns = append(out.Filters[i].Patterns, pattern)
					}
				}
			}
		}
	}
	data, err := yaml.Marshal(&out)
	if err != nil {
		return "", fmt.Errorf("failed to serialise config: %w", err)
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by docker-logs-dashboard config-builder\n")
	buf.WriteString("# Merge these events/filters into your main config.yaml\n\n")
	buf.Write(data)
	return buf.String(), nil
}

// ParseConfigDrafts parses a saved config YAML back into a slice of EventDraft
// so it can be loaded into the form editor. Each event becomes one draft; if a
// filter with the same pattern exists it is linked back via AddFilter/FilterName.
func ParseConfigDrafts(yamlData []byte) ([]EventDraft, error) {
	var out outputConfig
	if err := yaml.Unmarshal(yamlData, &out); err != nil {
		return nil, fmt.Errorf("invalid YAML: %w", err)
	}

	// Build a reverse map: pattern → filterName (first match)
	patternToFilter := make(map[string]string)
	for _, f := range out.Filters {
		for _, p := range f.Patterns {
			if _, exists := patternToFilter[p]; !exists {
				patternToFilter[p] = f.Name
			}
		}
	}

	drafts := make([]EventDraft, 0, len(out.Events))
	for _, e := range out.Events {
		d := EventDraft{
			EventName: e.Name,
			Pattern:   e.Pattern,
			State:     e.State,
		}
		if fn, ok := patternToFilter[e.Pattern]; ok {
			d.AddFilter = true
			d.FilterName = fn
		}
		drafts = append(drafts, d)
	}

	// If there are filters whose patterns don't correspond to any event, append
	// placeholder drafts so they can still be edited.
	evtPatterns := make(map[string]bool)
	for _, e := range out.Events {
		evtPatterns[e.Pattern] = true
	}
	for _, f := range out.Filters {
		for _, p := range f.Patterns {
			if !evtPatterns[p] {
				drafts = append(drafts, EventDraft{
					EventName:  strings.TrimSpace(f.Name + "-filter"),
					Pattern:    p,
					State:      "",
					AddFilter:  true,
					FilterName: f.Name,
				})
			}
		}
	}

	return drafts, nil
}
